### ISSUE TITLE
8. Система повинна надавати користувачу можливість коментування запису.

### ISSUE THREAD

**Issue by AndriiSeverin** [vladaerastova/TPPS#5]
https://github.com/vladaerastova/TPPS/blob/0251777872ab1e14275f2fc20f9a6c1290b433d6/Lab2.txt#L9

Можливість коментування записів буде надана всім користувачам? Яким чином у такому разі вони будуть ідентифікуватись чи всі коментарі будуть анонімними?
Можливо, варто передбачити реєстрацію користувачів; відповідно лише зареєстровані користувачі будуть мати можливість коментувати записи (а незареєстровані лише переглядати існуючі коментарі).

**Comment by vladaerastova** [comment]
Так як користувач може лише залишати коментарі, не бачу необхідності додавати реєстрацію.
Ідентифікуватись будуть за ім'ям(додано до вимог).
